### ISSUE TITLE
菜单指令发生未知错误

### ISSUE THREAD

**Issue by continentlht** [axlmly/koishi-plugin-axlmly-role-playing-game#1]
插件配置如下（没动）：
![Uploading AD}SS~KZEF[RK5SMX]P4H2W.jpg…]()
![WF@NAKFPFMMU55 27 %G72I](https://github.com/user-attachments/assets/e5d12af5-d8a8-4204-9be3-774381a22563)
下载方式：插件市场直接下载
日志：
![JGU1 VA{8N TF3I}6)CF5D3](https://github.com/user-attachments/assets/fe88e5f8-a977-4499-8cd3-7d48991e1d6a)
目录列表：
![3GHJ9O%B@E8R7X7ID9Y1SK5](https://github.com/user-attachments/assets/91245310-a381-40af-9b07-7c52f68c7cbf)
![CVWX0J~WW`@6WL FHB`4476](https://github.com/user-attachments/assets/f197d74c-24be-47bf-ba40-e41338996ce9)

**Comment by continentlht** [comment]
![AD}SS~KZEF RK5SMX P4H2W](https://github.com/user-attachments/assets/4d4ef0bb-0321-4b94-8181-0ed6fa08b2d2)
第一张图上传失败了

**Comment by axlmly** [comment]
提供pptr是什么插件

**Comment by flymyd** [comment]
> 提供pptr是什么插件

同问题，环境linux docker，使用Koishijs官方带pptr的docker。自带pptr和@shangxueink/puppeteer-without-canvas v1.1.0都不行。作者是在win环境下测的吗？

**Comment by axlmly** [comment]
> > 提供pptr是什么插件
> 
> 同问题，环境linux docker，使用Koishijs官方带pptr的docker。自带pptr和@shangxueink/puppeteer-without-canvas v1.1.0都不行。作者是在win环境下测的吗？

是,我没有除win外的其他设备测试

**Comment by flymyd** [comment]
> > > 提供pptr是什么插件
> > 
> > 
> > 同问题，环境linux docker，使用Koishijs官方带pptr的docker。自带pptr和@shangxueink/puppeteer-without-canvas v1.1.0都不行。作者是在win环境下测的吗？
> 
> 是,我没有除win外的其他设备测试

刚才开了个仓库试了下，page.goto(menuPath)有问题。而且加file://协议头也不行

**Comment by axlmly** [comment]
> > > > 提供pptr是什么插件
> > > 
> > > 
> > > 同问题，环境linux docker，使用Koishijs官方带pptr的docker。自带pptr和@shangxueink/puppeteer-without-canvas v1.1.0都不行。作者是在win环境下测的吗？
> > 
> > 
> > 是,我没有除win外的其他设备测试
> 
> 刚才开了个仓库试了下，page.goto(menuPath)有问题。而且加file://协议头也不行

是的,是路径问题,已经在解决了

**Comment by axlmly** [comment]
更新版本

**Comment by flymyd** [comment]
1.7.0问题依旧

**Comment by axlmly** [comment]
> 1.7.0问题依旧

日志

**Comment by flymyd** [comment]
> > 1.7.0问题依旧
> 
> 日志

command menu 
                        ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
                            at <instance_members_initializer> (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
                            at new Callback (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
                            at CallbackRegistry.create (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
                            at Connection._rawSend (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:88:26)
                            at CdpCDPSession.send (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
                            at navigate (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:164:51)
                            at CdpFrame.goto (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:142:17)
                            at CdpFrame.<anonymous> (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
                            at CdpPage.goto (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:585:43)
                            at _Command.<anonymous> (/koishi/node_modules/koishi-plugin-axlmly-role-playing-game/lib/index.js:12302:16)

**Comment by flymyd** [comment]
环境Docker部署：
System:

OS: Linux 6.6 Alpine Linux

CPU: (6) x64 Genuine Intel(R) CPU 0000 @ 3.00GHz

Binaries:

Node: 20.14.0

Yarn: 4.1.1

Koishi:

Core: 4.18.0

Console: 5.28.4

**Comment by axlmly** [comment]
你在报错的那行上面加上 const file = file:/// 
报错的那行改成await page.goto(file + menuPath);
试试

**Comment by flymyd** [comment]
> 你在报错的那行上面加上 const file = file:/// 报错的那行改成await page.goto(file + menuPath); 试试

之前试过，file协议没法跳过去，很怪

**Comment by continentlht** [comment]
> 提供pptr是什么插件

![image](https://github.com/user-attachments/assets/89363135-2d3e-40d2-8e24-010c0b2aa556)

**Comment by flymyd** [comment]
> > 提供pptr是什么插件
> 
> ![image](https://private-user-images.githubusercontent.com/138009699/377346489-89363135-2d3e-40d2-8e24-010c0b2aa556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDg0NjMsIm5iZiI6MTcyOTE0ODE2MywicGF0aCI6Ii8xMzgwMDk2OTkvMzc3MzQ2NDg5LTg5MzYzMTM1LTJkM2UtNDBkMi04ZTI0LTAxMGMwYjJhYTU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDUzOWY2MDVjNTUxM2M1ODI0OGIxY2YzY2RiOWI0NmE0OTgxZjNhZmNlZjk3ZjNjY2E5YWViNmUyYzAzNWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4Yxx359x4TH_kIu8DhzOeqVQCY76W4w1XftxL_V-pKo)

@shangxueink/koishi-plugin-puppeteer-without-canvas V1.1.0
以及
koishi-plugin-puppeteer V3.9.0
都不行

**Comment by flymyd** [comment]
刚试了下@seidko/puppeteer V3.5.1同样
